// AUTO-GENERATED by anchor/scripts/bootstrap.ts — do not edit by hand.
// Devnet deployment addresses for ChamaChain v2.
import type { ClusterConfig } from "./types";

export const devnet: ClusterConfig = {
  CLUSTER: "devnet",
  RPC_ENDPOINT: "https://api.devnet.solana.com",
  PROGRAM_ID: "8gkPp9gCALdkTvzPVk6LjVw4TRg6iKkzaRLU465y9Gye",
  CONFIG_PDA: "5daiQeu14WCXMpovFokDenULJC1CsWN57SkJjhbvd2g3",
  MINT_AUTHORITY_PDA: "6BgQugkLj3ZMoDx1wek4GdMRZGwrf7wXWJjJJvy5fVkT",
  USDT_MINT: "2MLRaqL8Y9zGEgSHZ3w2kowF8maPakWLYptX9m4QBmie",
  CHM_MINT: "HtFozfffrxCiqTMCUGSsgoiqxyRphb2ytZyWgrTnMaPZ",
  TOKEN_DECIMALS: 6,
  // DEVNET-ONLY mock-USDT faucet authority. This secret is intentionally public:
  // it can only mint a worthless test token on devnet. Never reuse this pattern
  // for a real mint or for mainnet.
  FAUCET_AUTHORITY_SECRET: [
    219, 123, 152, 22, 148, 181, 73, 39, 16, 171, 127, 66, 210, 240, 224, 110, 70, 2, 122, 175,
    189, 100, 106, 1, 48, 66, 191, 224, 174, 132, 234, 68, 231, 134, 165, 166, 241, 237, 210, 96,
    197, 102, 41, 143, 137, 99, 213, 17, 15, 251, 117, 175, 192, 68, 72, 159, 68, 97, 124, 216,
    107, 52, 25, 24,
  ],
};
